# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DockerProjectAo.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DockerProjectConst_pb2 as DockerProjectConst__pb2
import DockerProjectCommon_pb2 as DockerProjectCommon__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x44ockerProjectAo.proto\x12\x12\x64ockerProjectProto\x1a\x18\x44ockerProjectConst.proto\x1a\x19\x44ockerProjectCommon.proto2k\n\x0f\x44ockerProjectAo\x12X\n\x0bGetItemInfo\x12\".dockerProjectProto.GetItemInfoReq\x1a#.dockerProjectProto.GetItemInfoResp\"\x00\x42\x15Z\x13\x64ockerProjectProto/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DockerProjectAo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023dockerProjectProto/'
  _globals['_DOCKERPROJECTAO']._serialized_start=98
  _globals['_DOCKERPROJECTAO']._serialized_end=205
# @@protoc_insertion_point(module_scope)
