# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DockerProjectCommon.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x44ockerProjectCommon.proto\x12\x12\x64ockerProjectProto\"/\n\rRequestHeader\x12\x0e\n\x06reqSeq\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\"/\n\x0eResponseHeader\x12\r\n\x05\x65rrno\x18\x01 \x01(\r\x12\x0e\n\x06\x65rrmsg\x18\x02 \x01(\t\"V\n\x0eGetItemInfoReq\x12\x34\n\treqHeader\x18\x01 \x01(\x0b\x32!.dockerProjectProto.RequestHeader\x12\x0e\n\x06itemId\x18\x02 \x01(\x03\"\xf1\x01\n\x0fGetItemInfoResp\x12\x36\n\nrespHeader\x18\x01 \x01(\x0b\x32\".dockerProjectProto.ResponseHeader\x12\n\n\x02id\x18\x02 \x01(\x03\x12\x16\n\x0eitemSourceName\x18\x03 \x01(\t\x12\x12\n\nitemCnName\x18\x04 \x01(\t\x12\x17\n\x0fsellOnlineCount\x18\x05 \x01(\x05\x12\x0e\n\x06picUrl\x18\x06 \x01(\t\x12\x0e\n\x06prices\x18\x07 \x01(\x02\x12\x10\n\x08\x63urrency\x18\x08 \x01(\t\x12\x0f\n\x07\x61\x64\x64time\x18\t \x01(\x03\x12\x12\n\nmodifytime\x18\n \x01(\tB\x15Z\x13\x64ockerProjectProto/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DockerProjectCommon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023dockerProjectProto/'
  _globals['_REQUESTHEADER']._serialized_start=49
  _globals['_REQUESTHEADER']._serialized_end=96
  _globals['_RESPONSEHEADER']._serialized_start=98
  _globals['_RESPONSEHEADER']._serialized_end=145
  _globals['_GETITEMINFOREQ']._serialized_start=147
  _globals['_GETITEMINFOREQ']._serialized_end=233
  _globals['_GETITEMINFORESP']._serialized_start=236
  _globals['_GETITEMINFORESP']._serialized_end=477
# @@protoc_insertion_point(module_scope)
