# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DockerProjectConst.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x44ockerProjectConst.proto\x12\x12\x64ockerProjectProto*=\n\x0bRequestType\x12\x17\n\x13REQUEST_TYPE_COMMON\x10\x00\x12\x15\n\x11REQUEST_TYPE_GRPC\x10\x01*k\n\rValidUserType\x12\x1a\n\x16VALID_USER_TYPE_COMMON\x10\x00\x12\x1e\n\x1aVALID_USER_TYPE_BLACK_LIST\x10\x01\x12\x1e\n\x1aVALID_USER_TYPE_WHITE_LIST\x10\x02\x42\x15Z\x13\x64ockerProjectProto/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DockerProjectConst_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023dockerProjectProto/'
  _globals['_REQUESTTYPE']._serialized_start=48
  _globals['_REQUESTTYPE']._serialized_end=109
  _globals['_VALIDUSERTYPE']._serialized_start=111
  _globals['_VALIDUSERTYPE']._serialized_end=218
# @@protoc_insertion_point(module_scope)
